[package]
name = "tow-service"
version.workspace = true
edition.workspace = true
description = "拖车服务 - 提供车辆管理和配置选项"

[lib]
name = "tow_service"
path = "src/lib.rs"

[[bin]]
name = "tow-service"
path = "src/main.rs"

[dependencies]
tracing = "0.1"
tracing-subscriber.workspace = true
tokio.workspace = true
common.workspace = true
sqlx = { workspace = true, features = ["json"] }
serde.workspace = true
serde_json.workspace = true
log.workspace = true

thiserror.workspace = true
chrono.workspace = true
axum.workspace = true
reqwest.workspace = true

# gRPC
tonic.workspace = true
grpc-proto.workspace = true
prost.workspace = true
futures-util.workspace = true

