[package]
name = "grpc-proto"
version.workspace = true
edition.workspace = true
[lib]
name = "grpc_proto"
path = "src/lib.rs"

description = "gRPC 协议定义 - 提供 Proto 文件生成的 Rust 代码"

[dependencies]
tracing = "0.1"
tonic.workspace = true
prost.workspace = true
tonic-prost.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true

[build-dependencies]
tonic-prost-build.workspace = true
prost-build.workspace = true
