[package]
name = "auth-core"
version.workspace = true
edition.workspace = true
[lib]
name = "auth_core"
path = "src/lib.rs"


[dependencies]
tracing = "0.1"
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
jsonwebtoken = { workspace = true, features = ["rust_crypto"] }
common.workspace = true
chrono.workspace = true

# HTTP 框架（用于中间件）
axum.workspace = true
async-trait.workspace = true

[dev-dependencies]
tokio-test = "0.4"