/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | '//(index)'
      | '//second'
    >,
    '//(index)': RouteRecordInfo<
      '//(index)',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '//second': RouteRecordInfo<
      '//second',
      '/second',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/accounts/AccountDetailPage': RouteRecordInfo<
      '/accounts/AccountDetailPage',
      '/accounts/AccountDetailPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/accounts/AccountListPage': RouteRecordInfo<
      '/accounts/AccountListPage',
      '/accounts/AccountListPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/ContentDetailPage': RouteRecordInfo<
      '/content/ContentDetailPage',
      '/content/ContentDetailPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/ContentListPage': RouteRecordInfo<
      '/content/ContentListPage',
      '/content/ContentListPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/crawl/CrawlHistoryPage': RouteRecordInfo<
      '/crawl/CrawlHistoryPage',
      '/crawl/CrawlHistoryPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/crawl/SourceListPage': RouteRecordInfo<
      '/crawl/SourceListPage',
      '/crawl/SourceListPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/DashboardPage': RouteRecordInfo<
      '/DashboardPage',
      '/DashboardPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/insights/InsightListPage': RouteRecordInfo<
      '/insights/InsightListPage',
      '/insights/InsightListPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/publish/PublishTaskPage': RouteRecordInfo<
      '/publish/PublishTaskPage',
      '/publish/PublishTaskPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/publish/PublishWizard': RouteRecordInfo<
      '/publish/PublishWizard',
      '/publish/PublishWizard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/publish/ScheduleListPage': RouteRecordInfo<
      '/publish/ScheduleListPage',
      '/publish/ScheduleListPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rewrite/LLMProviderSettings': RouteRecordInfo<
      '/rewrite/LLMProviderSettings',
      '/rewrite/LLMProviderSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rewrite/RewriteEditorPage': RouteRecordInfo<
      '/rewrite/RewriteEditorPage',
      '/rewrite/RewriteEditorPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rewrite/RewriteTaskPage': RouteRecordInfo<
      '/rewrite/RewriteTaskPage',
      '/rewrite/RewriteTaskPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/stats/StatsDashboard': RouteRecordInfo<
      '/stats/StatsDashboard',
      '/stats/StatsDashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
        | '//(index)'
        | '//second'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/index/(index).vue': {
      routes:
        | '//(index)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/index/second.vue': {
      routes:
        | '//second'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/accounts/AccountDetailPage.vue': {
      routes:
        | '/accounts/AccountDetailPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/accounts/AccountListPage.vue': {
      routes:
        | '/accounts/AccountListPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/content/ContentDetailPage.vue': {
      routes:
        | '/content/ContentDetailPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/content/ContentListPage.vue': {
      routes:
        | '/content/ContentListPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/crawl/CrawlHistoryPage.vue': {
      routes:
        | '/crawl/CrawlHistoryPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/crawl/SourceListPage.vue': {
      routes:
        | '/crawl/SourceListPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/DashboardPage.vue': {
      routes:
        | '/DashboardPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/insights/InsightListPage.vue': {
      routes:
        | '/insights/InsightListPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/publish/PublishTaskPage.vue': {
      routes:
        | '/publish/PublishTaskPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/publish/PublishWizard.vue': {
      routes:
        | '/publish/PublishWizard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/publish/ScheduleListPage.vue': {
      routes:
        | '/publish/ScheduleListPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/rewrite/LLMProviderSettings.vue': {
      routes:
        | '/rewrite/LLMProviderSettings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/rewrite/RewriteEditorPage.vue': {
      routes:
        | '/rewrite/RewriteEditorPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/rewrite/RewriteTaskPage.vue': {
      routes:
        | '/rewrite/RewriteTaskPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/stats/StatsDashboard.vue': {
      routes:
        | '/stats/StatsDashboard'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
