apiVersion: v2
name: erp-new
description: erp_new 全栈微服务管理平台 Helm Chart
type: application
version: 0.3.0
appVersion: "20260915.1"
keywords:
  - erp-new
  - rust
  - microservices
  - vue
  - quasar
maintainers:
  - name: canplay
    email: canplay@example.com
home: https://github.com/canplay/erp_new
