/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/analytics/': RouteRecordInfo<
      '/analytics/',
      '/analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/analytics/AnalyticsDialogs': RouteRecordInfo<
      '/analytics/AnalyticsDialogs',
      '/analytics/AnalyticsDialogs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/billing/invoice-detail/': RouteRecordInfo<
      '/billing/invoice-detail/',
      '/billing/invoice-detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/billing/invoices/': RouteRecordInfo<
      '/billing/invoices/',
      '/billing/invoices',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/': RouteRecordInfo<
      '/catalog/',
      '/catalog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/CatalogBrandsTab': RouteRecordInfo<
      '/catalog/CatalogBrandsTab',
      '/catalog/CatalogBrandsTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/CatalogCategoriesTab': RouteRecordInfo<
      '/catalog/CatalogCategoriesTab',
      '/catalog/CatalogCategoriesTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/CatalogProductDetailDialog': RouteRecordInfo<
      '/catalog/CatalogProductDetailDialog',
      '/catalog/CatalogProductDetailDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/CatalogProductDialogs': RouteRecordInfo<
      '/catalog/CatalogProductDialogs',
      '/catalog/CatalogProductDialogs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/CatalogProductFilters': RouteRecordInfo<
      '/catalog/CatalogProductFilters',
      '/catalog/CatalogProductFilters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/CatalogProductPagination': RouteRecordInfo<
      '/catalog/CatalogProductPagination',
      '/catalog/CatalogProductPagination',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/CatalogProductsTab': RouteRecordInfo<
      '/catalog/CatalogProductsTab',
      '/catalog/CatalogProductsTab',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/catalog/CatalogProductTable': RouteRecordInfo<
      '/catalog/CatalogProductTable',
      '/catalog/CatalogProductTable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/daily-control/': RouteRecordInfo<
      '/daily-control/',
      '/daily-control',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/equipment/': RouteRecordInfo<
      '/equipment/',
      '/equipment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/equipment/detail/': RouteRecordInfo<
      '/equipment/detail/',
      '/equipment/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/groups/': RouteRecordInfo<
      '/groups/',
      '/groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/health/': RouteRecordInfo<
      '/health/',
      '/health',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hidden-danger/': RouteRecordInfo<
      '/hidden-danger/',
      '/hidden-danger',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/impersonation/': RouteRecordInfo<
      '/impersonation/',
      '/impersonation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/knowledge-graph/': RouteRecordInfo<
      '/knowledge-graph/',
      '/knowledge-graph',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/messages/': RouteRecordInfo<
      '/messages/',
      '/messages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monthly-report/': RouteRecordInfo<
      '/monthly-report/',
      '/monthly-report',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/personnel/': RouteRecordInfo<
      '/personnel/',
      '/personnel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/personnel/PersonnelCertVerify': RouteRecordInfo<
      '/personnel/PersonnelCertVerify',
      '/personnel/PersonnelCertVerify',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/regulatory/': RouteRecordInfo<
      '/regulatory/',
      '/regulatory',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/regulatory/RegulatoryFeedbackSection': RouteRecordInfo<
      '/regulatory/RegulatoryFeedbackSection',
      '/regulatory/RegulatoryFeedbackSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/roles/': RouteRecordInfo<
      '/roles/',
      '/roles',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/roles/detail/': RouteRecordInfo<
      '/roles/detail/',
      '/roles/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tenants/': RouteRecordInfo<
      '/tenants/',
      '/tenants',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tenants/detail/': RouteRecordInfo<
      '/tenants/detail/',
      '/tenants/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tickets/': RouteRecordInfo<
      '/tickets/',
      '/tickets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tickets/TicketCommentsSection': RouteRecordInfo<
      '/tickets/TicketCommentsSection',
      '/tickets/TicketCommentsSection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tickets/TicketDetailDialog': RouteRecordInfo<
      '/tickets/TicketDetailDialog',
      '/tickets/TicketDetailDialog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/': RouteRecordInfo<
      '/users/',
      '/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/users/detail/': RouteRecordInfo<
      '/users/detail/',
      '/users/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/webhooks/': RouteRecordInfo<
      '/webhooks/',
      '/webhooks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/webhooks/detail/': RouteRecordInfo<
      '/webhooks/detail/',
      '/webhooks/detail',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/weekly-check/': RouteRecordInfo<
      '/weekly-check/',
      '/weekly-check',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/analytics/index.vue': {
      routes:
        | '/analytics/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/analytics/AnalyticsDialogs.vue': {
      routes:
        | '/analytics/AnalyticsDialogs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/billing/invoice-detail/index.vue': {
      routes:
        | '/billing/invoice-detail/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/billing/invoices/index.vue': {
      routes:
        | '/billing/invoices/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/catalog/index.vue': {
      routes:
        | '/catalog/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/catalog/CatalogBrandsTab.vue': {
      routes:
        | '/catalog/CatalogBrandsTab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/catalog/CatalogCategoriesTab.vue': {
      routes:
        | '/catalog/CatalogCategoriesTab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/catalog/CatalogProductDetailDialog.vue': {
      routes:
        | '/catalog/CatalogProductDetailDialog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/catalog/CatalogProductDialogs.vue': {
      routes:
        | '/catalog/CatalogProductDialogs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/catalog/CatalogProductFilters.vue': {
      routes:
        | '/catalog/CatalogProductFilters'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/catalog/CatalogProductPagination.vue': {
      routes:
        | '/catalog/CatalogProductPagination'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/catalog/CatalogProductsTab.vue': {
      routes:
        | '/catalog/CatalogProductsTab'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/catalog/CatalogProductTable.vue': {
      routes:
        | '/catalog/CatalogProductTable'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/daily-control/index.vue': {
      routes:
        | '/daily-control/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/equipment/index.vue': {
      routes:
        | '/equipment/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/equipment/detail/index.vue': {
      routes:
        | '/equipment/detail/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/groups/index.vue': {
      routes:
        | '/groups/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/health/index.vue': {
      routes:
        | '/health/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/hidden-danger/index.vue': {
      routes:
        | '/hidden-danger/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/impersonation/index.vue': {
      routes:
        | '/impersonation/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/knowledge-graph/index.vue': {
      routes:
        | '/knowledge-graph/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/messages/index.vue': {
      routes:
        | '/messages/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/monthly-report/index.vue': {
      routes:
        | '/monthly-report/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/personnel/index.vue': {
      routes:
        | '/personnel/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/personnel/PersonnelCertVerify.vue': {
      routes:
        | '/personnel/PersonnelCertVerify'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/regulatory/index.vue': {
      routes:
        | '/regulatory/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/regulatory/RegulatoryFeedbackSection.vue': {
      routes:
        | '/regulatory/RegulatoryFeedbackSection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/roles/index.vue': {
      routes:
        | '/roles/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/roles/detail/index.vue': {
      routes:
        | '/roles/detail/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tenants/index.vue': {
      routes:
        | '/tenants/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tenants/detail/index.vue': {
      routes:
        | '/tenants/detail/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tickets/index.vue': {
      routes:
        | '/tickets/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tickets/TicketCommentsSection.vue': {
      routes:
        | '/tickets/TicketCommentsSection'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/tickets/TicketDetailDialog.vue': {
      routes:
        | '/tickets/TicketDetailDialog'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users/index.vue': {
      routes:
        | '/users/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/users/detail/index.vue': {
      routes:
        | '/users/detail/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/webhooks/index.vue': {
      routes:
        | '/webhooks/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/webhooks/detail/index.vue': {
      routes:
        | '/webhooks/detail/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/weekly-check/index.vue': {
      routes:
        | '/weekly-check/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
