// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditLog {
    #[prost(int64, tag = "1" )]
    pub id: i64,
    #[prost(int64, tag = "2" )]
    pub user_id: i64,
    #[prost(string, tag = "3" )]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "4" )]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(string, tag = "5" )]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(enumeration = "AuditAction" , tag = "6" )]
    pub action: i32,
    #[prost(string, tag = "7" )]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "8" )]
    pub resource_id: i64,
    #[prost(string, tag = "9" )]
    pub description: ::prost::alloc::string::String,
    #[prost(map = "string, string" , tag = "10" )]
    pub old_data: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, string" , tag = "11" )]
    pub new_data: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(int64, tag = "12" )]
    pub created_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogActionRequest {
    #[prost(int64, tag = "1" )]
    pub user_id: i64,
    #[prost(string, tag = "2" )]
    pub username: ::prost::alloc::string::String,
    #[prost(enumeration = "AuditAction" , tag = "3" )]
    pub action: i32,
    #[prost(string, tag = "4" )]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "5" )]
    pub resource_id: i64,
    #[prost(string, tag = "6" )]
    pub description: ::prost::alloc::string::String,
    #[prost(map = "string, string" , tag = "7" )]
    pub old_data: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(map = "string, string" , tag = "8" )]
    pub new_data: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogActionResponse {
    #[prost(int64, tag = "1" )]
    pub id: i64,
    #[prost(bool, tag = "2" )]
    pub success: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListLogsRequest {
    #[prost(int32, tag = "1" )]
    pub page: i32,
    #[prost(int32, tag = "2" )]
    pub page_size: i32,
    #[prost(int64, tag = "3" )]
    pub user_id: i64,
    #[prost(enumeration = "AuditAction" , tag = "4" )]
    pub action: i32,
    #[prost(string, tag = "5" )]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "6" )]
    pub resource_id: i64,
    #[prost(string, tag = "7" )]
    pub keyword: ::prost::alloc::string::String,
    #[prost(string, tag = "8" )]
    pub start_time: ::prost::alloc::string::String,
    #[prost(string, tag = "9" )]
    pub end_time: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListLogsResponse {
    #[prost(message, repeated, tag = "1" )]
    pub logs: ::prost::alloc::vec::Vec<AuditLog>,
    #[prost(int64, tag = "2" )]
    pub total: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLogRequest {
    #[prost(int64, tag = "1" )]
    pub id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLogResponse {
    #[prost(message, optional, tag = "1" )]
    pub log: ::core::option::Option<AuditLog>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginLogInfo {
    #[prost(int64, tag = "1" )]
    pub id: i64,
    #[prost(int64, tag = "2" )]
    pub user_id: i64,
    #[prost(string, tag = "3" )]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "4" )]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(string, tag = "5" )]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(bool, tag = "6" )]
    pub success: bool,
    #[prost(string, tag = "7" )]
    pub fail_reason: ::prost::alloc::string::String,
    #[prost(string, tag = "8" )]
    pub login_method: ::prost::alloc::string::String,
    #[prost(int64, tag = "9" )]
    pub created_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListLoginLogsRequest {
    #[prost(int32, tag = "1" )]
    pub page: i32,
    #[prost(int32, tag = "2" )]
    pub page_size: i32,
    #[prost(int64, tag = "3" )]
    pub user_id: i64,
    #[prost(string, tag = "4" )]
    pub keyword: ::prost::alloc::string::String,
    #[prost(bool, tag = "5" )]
    pub success: bool,
    #[prost(string, tag = "6" )]
    pub start_time: ::prost::alloc::string::String,
    #[prost(string, tag = "7" )]
    pub end_time: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListLoginLogsResponse {
    #[prost(message, repeated, tag = "1" )]
    pub logs: ::prost::alloc::vec::Vec<LoginLogInfo>,
    #[prost(int64, tag = "2" )]
    pub total: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLoginLogRequest {
    #[prost(int64, tag = "1" )]
    pub id: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLoginLogResponse {
    #[prost(message, optional, tag = "1" )]
    pub log: ::core::option::Option<LoginLogInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClearLoginLogsRequest {
    #[prost(string, tag = "1" )]
    pub before_date: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClearLoginLogsResponse {
    #[prost(int64, tag = "1" )]
    pub cleared_count: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApiCallLogInfo {
    #[prost(int64, tag = "1" )]
    pub id: i64,
    #[prost(int64, tag = "2" )]
    pub user_id: i64,
    #[prost(string, tag = "3" )]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "4" )]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag = "5" )]
    pub path: ::prost::alloc::string::String,
    #[prost(int32, tag = "6" )]
    pub status_code: i32,
    #[prost(int64, tag = "7" )]
    pub duration_ms: i64,
    #[prost(string, tag = "8" )]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(string, tag = "9" )]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(string, tag = "10" )]
    pub request_body: ::prost::alloc::string::String,
    #[prost(string, tag = "11" )]
    pub response_body: ::prost::alloc::string::String,
    #[prost(int64, tag = "12" )]
    pub created_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListApiCallLogsRequest {
    #[prost(int32, tag = "1" )]
    pub page: i32,
    #[prost(int32, tag = "2" )]
    pub page_size: i32,
    #[prost(int64, tag = "3" )]
    pub user_id: i64,
    #[prost(string, tag = "4" )]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag = "5" )]
    pub path: ::prost::alloc::string::String,
    #[prost(int32, tag = "6" )]
    pub status_code: i32,
    #[prost(string, tag = "7" )]
    pub start_time: ::prost::alloc::string::String,
    #[prost(string, tag = "8" )]
    pub end_time: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListApiCallLogsResponse {
    #[prost(message, repeated, tag = "1" )]
    pub logs: ::prost::alloc::vec::Vec<ApiCallLogInfo>,
    #[prost(int64, tag = "2" )]
    pub total: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetApiCallLogRequest {
    #[prost(int64, tag = "1" )]
    pub id: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetApiCallLogResponse {
    #[prost(message, optional, tag = "1" )]
    pub log: ::core::option::Option<ApiCallLogInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditStats {
    #[prost(int64, tag = "1" )]
    pub total_count: i64,
    #[prost(int64, tag = "2" )]
    pub today_count: i64,
    #[prost(int64, tag = "3" )]
    pub week_count: i64,
    #[prost(map = "int32, int64" , tag = "4" )]
    pub by_action: ::std::collections::HashMap<i32, i64>,
    #[prost(map = "string, int64" , tag = "5" )]
    pub by_resource_type: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        i64,
    >,
    #[prost(message, repeated, tag = "6" )]
    pub top_users: ::prost::alloc::vec::Vec<TopUser>,
    #[prost(message, repeated, tag = "7" )]
    pub top_resources: ::prost::alloc::vec::Vec<TopResource>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TopUser {
    #[prost(int64, tag = "1" )]
    pub user_id: i64,
    #[prost(string, tag = "2" )]
    pub username: ::prost::alloc::string::String,
    #[prost(int64, tag = "3" )]
    pub count: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TopResource {
    #[prost(string, tag = "1" )]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "2" )]
    pub resource_id: i64,
    #[prost(int64, tag = "3" )]
    pub count: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStatsRequest {
    #[prost(string, tag = "1" )]
    pub period: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatsResponse {
    #[prost(message, optional, tag = "1" )]
    pub stats: ::core::option::Option<AuditStats>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ArchiveLogsRequest {
    #[prost(string, tag = "1" )]
    pub start_time: ::prost::alloc::string::String,
    #[prost(string, tag = "2" )]
    pub end_time: ::prost::alloc::string::String,
    #[prost(int64, tag = "3" )]
    pub archive_user_id: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ArchiveLogsResponse {
    #[prost(int64, tag = "1" )]
    pub archived_count: i64,
    #[prost(string, tag = "2" )]
    pub archive_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExportLogsRequest {
    #[prost(string, tag = "1" )]
    pub start_time: ::prost::alloc::string::String,
    #[prost(string, tag = "2" )]
    pub end_time: ::prost::alloc::string::String,
    #[prost(string, tag = "3" )]
    pub format: ::prost::alloc::string::String,
    #[prost(string, tag = "4" )]
    pub log_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExportLogsResponse {
    #[prost(bytes = "vec" , tag = "1" )]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2" )]
    pub filename: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AuditAction {
    Create = 0,
    Update = 1,
    Delete = 2,
    Login = 3,
    Logout = 4,
    Export = 5,
    Import = 6,
    Other = 99,
}
impl AuditAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Create => "CREATE" ,
            Self::Update => "UPDATE" ,
            Self::Delete => "DELETE" ,
            Self::Login => "LOGIN" ,
            Self::Logout => "LOGOUT" ,
            Self::Export => "EXPORT" ,
            Self::Import => "IMPORT" ,
            Self::Other => "OTHER" ,
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CREATE" => Some(Self::Create),
            "UPDATE" => Some(Self::Update),
            "DELETE" => Some(Self::Delete),
            "LOGIN" => Some(Self::Login),
            "LOGOUT" => Some(Self::Logout),
            "EXPORT" => Some(Self::Export),
            "IMPORT" => Some(Self::Import),
            "OTHER" => Some(Self::Other),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod audit_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// 审计服务
    #[derive(Debug, Clone)]
    pub struct AuditServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AuditServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AuditServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AuditServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AuditServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// ============ 操作日志 ============
        pub async fn log_action(
            &mut self,
            request: impl tonic::IntoRequest<super::LogActionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LogActionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/LogAction" ,
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("audit.AuditService" , "LogAction" ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::ListLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListLogsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/ListLogs" ,
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("audit.AuditService" , "ListLogs" ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_log(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLogRequest>,
        ) -> std::result::Result<tonic::Response<super::GetLogResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/GetLog" ,
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("audit.AuditService" , "GetLog" ));
            self.inner.unary(req, path, codec).await
        }
        /// ============ 登录日志 ============
        pub async fn list_login_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::ListLoginLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListLoginLogsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/ListLoginLogs" ,
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("audit.AuditService" , "ListLoginLogs" ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_login_log(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLoginLogRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLoginLogResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/GetLoginLog" ,
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("audit.AuditService" , "GetLoginLog" ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn clear_login_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::ClearLoginLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClearLoginLogsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/ClearLoginLogs" ,
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("audit.AuditService" , "ClearLoginLogs" ));
            self.inner.unary(req, path, codec).await
        }
        /// ============ API 调用日志 ============
        pub async fn list_api_call_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::ListApiCallLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListApiCallLogsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/ListApiCallLogs" ,
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("audit.AuditService" , "ListApiCallLogs" ));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_api_call_log(
            &mut self,
            request: impl tonic::IntoRequest<super::GetApiCallLogRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetApiCallLogResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/GetApiCallLog" ,
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("audit.AuditService" , "GetApiCallLog" ));
            self.inner.unary(req, path, codec).await
        }
        /// ============ 日志统计 ============
        pub async fn get_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/GetStats" ,
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("audit.AuditService" , "GetStats" ));
            self.inner.unary(req, path, codec).await
        }
        /// ============ 日志归档 ============
        pub async fn archive_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::ArchiveLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ArchiveLogsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/ArchiveLogs" ,
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("audit.AuditService" , "ArchiveLogs" ));
            self.inner.unary(req, path, codec).await
        }
        /// ============ 日志导出 ============
        pub async fn export_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::ExportLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExportLogsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}" , e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/audit.AuditService/ExportLogs" ,
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("audit.AuditService" , "ExportLogs" ));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod audit_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AuditServiceServer.
    #[async_trait]
    pub trait AuditService: std::marker::Send + std::marker::Sync + 'static {
        /// ============ 操作日志 ============
        async fn log_action(
            &self,
            request: tonic::Request<super::LogActionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LogActionResponse>,
            tonic::Status,
        >;
        async fn list_logs(
            &self,
            request: tonic::Request<super::ListLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListLogsResponse>,
            tonic::Status,
        >;
        async fn get_log(
            &self,
            request: tonic::Request<super::GetLogRequest>,
        ) -> std::result::Result<tonic::Response<super::GetLogResponse>, tonic::Status>;
        /// ============ 登录日志 ============
        async fn list_login_logs(
            &self,
            request: tonic::Request<super::ListLoginLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListLoginLogsResponse>,
            tonic::Status,
        >;
        async fn get_login_log(
            &self,
            request: tonic::Request<super::GetLoginLogRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLoginLogResponse>,
            tonic::Status,
        >;
        async fn clear_login_logs(
            &self,
            request: tonic::Request<super::ClearLoginLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClearLoginLogsResponse>,
            tonic::Status,
        >;
        /// ============ API 调用日志 ============
        async fn list_api_call_logs(
            &self,
            request: tonic::Request<super::ListApiCallLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListApiCallLogsResponse>,
            tonic::Status,
        >;
        async fn get_api_call_log(
            &self,
            request: tonic::Request<super::GetApiCallLogRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetApiCallLogResponse>,
            tonic::Status,
        >;
        /// ============ 日志统计 ============
        async fn get_stats(
            &self,
            request: tonic::Request<super::GetStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatsResponse>,
            tonic::Status,
        >;
        /// ============ 日志归档 ============
        async fn archive_logs(
            &self,
            request: tonic::Request<super::ArchiveLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ArchiveLogsResponse>,
            tonic::Status,
        >;
        /// ============ 日志导出 ============
        async fn export_logs(
            &self,
            request: tonic::Request<super::ExportLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExportLogsResponse>,
            tonic::Status,
        >;
    }
    /// 审计服务
    #[derive(Debug)]
    pub struct AuditServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AuditServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AuditServiceServer<T>
    where
        T: AuditService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/audit.AuditService/LogAction" => {
                    #[allow(non_camel_case_types)]
                    struct LogActionSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::LogActionRequest>
                    for LogActionSvc<T> {
                        type Response = super::LogActionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LogActionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::log_action(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LogActionSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/audit.AuditService/ListLogs" => {
                    #[allow(non_camel_case_types)]
                    struct ListLogsSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::ListLogsRequest>
                    for ListLogsSvc<T> {
                        type Response = super::ListLogsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListLogsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::list_logs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListLogsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/audit.AuditService/GetLog" => {
                    #[allow(non_camel_case_types)]
                    struct GetLogSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::GetLogRequest>
                    for GetLogSvc<T> {
                        type Response = super::GetLogResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetLogRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::get_log(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetLogSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/audit.AuditService/ListLoginLogs" => {
                    #[allow(non_camel_case_types)]
                    struct ListLoginLogsSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::ListLoginLogsRequest>
                    for ListLoginLogsSvc<T> {
                        type Response = super::ListLoginLogsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListLoginLogsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::list_login_logs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListLoginLogsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/audit.AuditService/GetLoginLog" => {
                    #[allow(non_camel_case_types)]
                    struct GetLoginLogSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::GetLoginLogRequest>
                    for GetLoginLogSvc<T> {
                        type Response = super::GetLoginLogResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetLoginLogRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::get_login_log(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetLoginLogSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/audit.AuditService/ClearLoginLogs" => {
                    #[allow(non_camel_case_types)]
                    struct ClearLoginLogsSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::ClearLoginLogsRequest>
                    for ClearLoginLogsSvc<T> {
                        type Response = super::ClearLoginLogsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ClearLoginLogsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::clear_login_logs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ClearLoginLogsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/audit.AuditService/ListApiCallLogs" => {
                    #[allow(non_camel_case_types)]
                    struct ListApiCallLogsSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::ListApiCallLogsRequest>
                    for ListApiCallLogsSvc<T> {
                        type Response = super::ListApiCallLogsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListApiCallLogsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::list_api_call_logs(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListApiCallLogsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/audit.AuditService/GetApiCallLog" => {
                    #[allow(non_camel_case_types)]
                    struct GetApiCallLogSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::GetApiCallLogRequest>
                    for GetApiCallLogSvc<T> {
                        type Response = super::GetApiCallLogResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetApiCallLogRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::get_api_call_log(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetApiCallLogSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/audit.AuditService/GetStats" => {
                    #[allow(non_camel_case_types)]
                    struct GetStatsSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::GetStatsRequest>
                    for GetStatsSvc<T> {
                        type Response = super::GetStatsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStatsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::get_stats(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStatsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/audit.AuditService/ArchiveLogs" => {
                    #[allow(non_camel_case_types)]
                    struct ArchiveLogsSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::ArchiveLogsRequest>
                    for ArchiveLogsSvc<T> {
                        type Response = super::ArchiveLogsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ArchiveLogsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::archive_logs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ArchiveLogsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/audit.AuditService/ExportLogs" => {
                    #[allow(non_camel_case_types)]
                    struct ExportLogsSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::ExportLogsRequest>
                    for ExportLogsSvc<T> {
                        type Response = super::ExportLogsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ExportLogsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::export_logs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ExportLogsSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AuditServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "audit.AuditService";
    impl<T> tonic::server::NamedService for AuditServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
