// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Feedback {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    #[prost(enumeration = "FeedbackType", tag = "4")]
    pub r#type: i32,
    #[prost(enumeration = "FeedbackStatus", tag = "5")]
    pub status: i32,
    #[prost(enumeration = "FeedbackPriority", tag = "6")]
    pub priority: i32,
    #[prost(string, tag = "7")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub content: ::prost::alloc::string::String,
    /// 附件 URL
    #[prost(string, repeated, tag = "9")]
    pub attachments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 设备信息
    #[prost(string, tag = "10")]
    pub device_info: ::prost::alloc::string::String,
    /// App 版本
    #[prost(string, tag = "11")]
    pub app_version: ::prost::alloc::string::String,
    /// 扩展数据
    #[prost(map = "string, string", tag = "12")]
    pub extra: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 处理人
    #[prost(int64, tag = "13")]
    pub assigned_to: i64,
    #[prost(int64, tag = "14")]
    pub resolved_at: i64,
    #[prost(int64, tag = "15")]
    pub created_at: i64,
    #[prost(int64, tag = "16")]
    pub updated_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListFeedbacksRequest {
    #[prost(int32, tag = "1")]
    pub page: i32,
    #[prost(int32, tag = "2")]
    pub page_size: i32,
    #[prost(int64, tag = "3")]
    pub user_id: i64,
    #[prost(enumeration = "FeedbackType", tag = "4")]
    pub r#type: i32,
    #[prost(enumeration = "FeedbackStatus", tag = "5")]
    pub status: i32,
    #[prost(enumeration = "FeedbackPriority", tag = "6")]
    pub priority: i32,
    #[prost(string, tag = "7")]
    pub keyword: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListFeedbacksResponse {
    #[prost(message, repeated, tag = "1")]
    pub feedbacks: ::prost::alloc::vec::Vec<Feedback>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFeedbackRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFeedbackResponse {
    #[prost(message, optional, tag = "1")]
    pub feedback: ::core::option::Option<Feedback>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateFeedbackRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(enumeration = "FeedbackType", tag = "3")]
    pub r#type: i32,
    #[prost(string, tag = "4")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub attachments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "7")]
    pub device_info: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub app_version: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "9")]
    pub extra: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateFeedbackResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateFeedbackRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(enumeration = "FeedbackStatus", tag = "2")]
    pub status: i32,
    #[prost(enumeration = "FeedbackPriority", tag = "3")]
    pub priority: i32,
    #[prost(int64, tag = "4")]
    pub assigned_to: i64,
    /// 同时回复
    #[prost(string, tag = "5")]
    pub reply_content: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateFeedbackResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(enumeration = "FeedbackStatus", tag = "2")]
    pub status: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFeedbackRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFeedbackResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Reply {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub feedback_id: i64,
    #[prost(int64, tag = "3")]
    pub user_id: i64,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub content: ::prost::alloc::string::String,
    /// 是否管理员回复
    #[prost(bool, tag = "6")]
    pub is_admin: bool,
    #[prost(int64, tag = "7")]
    pub created_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddReplyRequest {
    #[prost(int64, tag = "1")]
    pub feedback_id: i64,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub content: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub is_admin: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddReplyResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(bool, tag = "2")]
    pub success: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListRepliesRequest {
    #[prost(int64, tag = "1")]
    pub feedback_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListRepliesResponse {
    #[prost(message, repeated, tag = "1")]
    pub replies: ::prost::alloc::vec::Vec<Reply>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeedbackStats {
    #[prost(int64, tag = "1")]
    pub total_count: i64,
    #[prost(int64, tag = "2")]
    pub open_count: i64,
    #[prost(int64, tag = "3")]
    pub in_progress_count: i64,
    #[prost(int64, tag = "4")]
    pub resolved_count: i64,
    #[prost(int64, tag = "5")]
    pub closed_count: i64,
    /// 按类型统计
    #[prost(map = "int32, int64", tag = "6")]
    pub by_type: ::std::collections::HashMap<i32, i64>,
    /// 按优先级统计
    #[prost(map = "int32, int64", tag = "7")]
    pub by_priority: ::std::collections::HashMap<i32, i64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStatsRequest {
    #[prost(int64, tag = "1")]
    pub period_start: i64,
    #[prost(int64, tag = "2")]
    pub period_end: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatsResponse {
    #[prost(message, optional, tag = "1")]
    pub stats: ::core::option::Option<FeedbackStats>,
}
/// 反馈类型
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FeedbackType {
    /// Bug 反馈
    Bug = 0,
    /// 功能建议
    Feature = 1,
    /// 问题咨询
    Question = 2,
    /// 投诉
    Complaint = 3,
    Other = 4,
}
impl FeedbackType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Bug => "BUG",
            Self::Feature => "FEATURE",
            Self::Question => "QUESTION",
            Self::Complaint => "COMPLAINT",
            Self::Other => "OTHER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BUG" => Some(Self::Bug),
            "FEATURE" => Some(Self::Feature),
            "QUESTION" => Some(Self::Question),
            "COMPLAINT" => Some(Self::Complaint),
            "OTHER" => Some(Self::Other),
            _ => None,
        }
    }
}
/// 反馈状态
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FeedbackStatus {
    Open = 0,
    InProgress = 1,
    Resolved = 2,
    Closed = 3,
}
impl FeedbackStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Open => "OPEN",
            Self::InProgress => "IN_PROGRESS",
            Self::Resolved => "RESOLVED",
            Self::Closed => "CLOSED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPEN" => Some(Self::Open),
            "IN_PROGRESS" => Some(Self::InProgress),
            "RESOLVED" => Some(Self::Resolved),
            "CLOSED" => Some(Self::Closed),
            _ => None,
        }
    }
}
/// 优先级
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FeedbackPriority {
    Low = 0,
    Medium = 1,
    High = 2,
    Urgent = 3,
}
impl FeedbackPriority {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Low => "LOW",
            Self::Medium => "MEDIUM",
            Self::High => "HIGH",
            Self::Urgent => "URGENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOW" => Some(Self::Low),
            "MEDIUM" => Some(Self::Medium),
            "HIGH" => Some(Self::High),
            "URGENT" => Some(Self::Urgent),
            _ => None,
        }
    }
}
