// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadRequest {
    #[prost(string, tag = "1")]
    pub filename: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub size: i64,
    #[prost(string, tag = "3")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(enumeration = "FileType", tag = "4")]
    pub file_type: i32,
    #[prost(string, tag = "5")]
    pub folder_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub user_id: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadResponse {
    #[prost(string, tag = "1")]
    pub file_id: ::prost::alloc::string::String,
    /// 预签名 URL
    #[prost(string, tag = "2")]
    pub upload_url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub upload_method: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadChunkRequest {
    #[prost(string, tag = "1")]
    pub file_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub chunk_index: i32,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadChunkResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(int32, tag = "2")]
    pub uploaded_chunks: i32,
    #[prost(int32, tag = "3")]
    pub total_chunks: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompleteUploadRequest {
    #[prost(string, tag = "1")]
    pub file_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompleteUploadResponse {
    #[prost(message, optional, tag = "1")]
    pub file: ::core::option::Option<FileInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub filename: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub original_filename: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub url: ::prost::alloc::string::String,
    #[prost(enumeration = "FileType", tag = "5")]
    pub file_type: i32,
    #[prost(string, tag = "6")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "7")]
    pub size: i64,
    #[prost(string, tag = "8")]
    pub folder_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "9")]
    pub user_id: i64,
    #[prost(string, tag = "10")]
    pub etag: ::prost::alloc::string::String,
    #[prost(int64, tag = "11")]
    pub created_at: i64,
    #[prost(int64, tag = "12")]
    pub updated_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListFilesRequest {
    #[prost(string, tag = "1")]
    pub folder_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
    #[prost(enumeration = "FileType", tag = "3")]
    pub file_type: i32,
    #[prost(string, tag = "4")]
    pub keyword: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub page: i32,
    #[prost(int32, tag = "6")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListFilesResponse {
    #[prost(message, repeated, tag = "1")]
    pub files: ::prost::alloc::vec::Vec<FileInfo>,
    #[prost(int64, tag = "2")]
    pub total: i64,
    #[prost(int64, tag = "3")]
    pub total_size: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFileRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFileResponse {
    #[prost(message, optional, tag = "1")]
    pub file: ::core::option::Option<FileInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFileRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 批量删除
    #[prost(string, repeated, tag = "2")]
    pub ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFileResponse {
    #[prost(int32, tag = "1")]
    pub count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDownloadUrlRequest {
    #[prost(string, tag = "1")]
    pub file_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
    /// 有效期（秒）
    #[prost(int32, tag = "3")]
    pub expires_in: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetDownloadUrlResponse {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub expires_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Folder {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub parent_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub user_id: i64,
    #[prost(string, tag = "5")]
    pub path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub children: ::prost::alloc::vec::Vec<Folder>,
    #[prost(int64, tag = "7")]
    pub file_count: i64,
    #[prost(int64, tag = "8")]
    pub created_at: i64,
    #[prost(int64, tag = "9")]
    pub updated_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListFoldersRequest {
    #[prost(string, tag = "1")]
    pub parent_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListFoldersResponse {
    #[prost(message, repeated, tag = "1")]
    pub folders: ::prost::alloc::vec::Vec<Folder>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateFolderRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub parent_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub user_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateFolderResponse {
    #[prost(message, optional, tag = "1")]
    pub folder: ::core::option::Option<Folder>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFolderRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 是否递归删除
    #[prost(bool, tag = "2")]
    pub recursive: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFolderResponse {
    #[prost(int32, tag = "1")]
    pub deleted_files: i32,
    #[prost(int32, tag = "2")]
    pub deleted_folders: i32,
}
/// 文件类型
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FileType {
    Image = 0,
    Video = 1,
    Audio = 2,
    Document = 3,
    Archive = 4,
    Other = 5,
}
impl FileType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Image => "IMAGE",
            Self::Video => "VIDEO",
            Self::Audio => "AUDIO",
            Self::Document => "DOCUMENT",
            Self::Archive => "ARCHIVE",
            Self::Other => "OTHER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "IMAGE" => Some(Self::Image),
            "VIDEO" => Some(Self::Video),
            "AUDIO" => Some(Self::Audio),
            "DOCUMENT" => Some(Self::Document),
            "ARCHIVE" => Some(Self::Archive),
            "OTHER" => Some(Self::Other),
            _ => None,
        }
    }
}
