// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListMessagesRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub page_size: i32,
    /// system, user, notice, todo
    #[prost(string, tag = "4")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub unread_only: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMessagesResponse {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    #[prost(int64, tag = "2")]
    pub total: i64,
    #[prost(int64, tag = "3")]
    pub unread_count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub sender: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_read: bool,
    #[prost(int64, tag = "8")]
    pub read_at: i64,
    #[prost(int64, tag = "9")]
    pub created_at: i64,
    /// 扩展数据（JSON）
    #[prost(message, optional, tag = "10")]
    pub data: ::core::option::Option<MessageData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageData {
    /// 点击后的动作
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
    /// 关联链接
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    /// 消息图片
    #[prost(string, tag = "3")]
    pub image: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "4")]
    pub extra: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMessageRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMessageResponse {
    #[prost(message, optional, tag = "1")]
    pub message: ::core::option::Option<Message>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMessageRequest {
    /// 接收者
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    /// 发送者（0 表示系统）
    #[prost(int64, tag = "2")]
    pub sender_id: i64,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub content: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub data: ::core::option::Option<MessageData>,
    /// 批量发送
    #[prost(int64, repeated, tag = "7")]
    pub user_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendMessageResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 实际发送数量
    #[prost(int32, tag = "2")]
    pub sent_count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkAsReadRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    /// 空表示全部已读
    #[prost(int64, repeated, tag = "2")]
    pub message_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MarkAsReadResponse {
    /// 标记数量
    #[prost(int32, tag = "1")]
    pub count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMessageRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    #[prost(int64, repeated, tag = "2")]
    pub message_ids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteMessageResponse {
    #[prost(int32, tag = "1")]
    pub count: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUnreadCountRequest {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
    /// 空表示全部
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUnreadCountResponse {
    #[prost(int64, tag = "1")]
    pub count: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTemplatesRequest {
    #[prost(int32, tag = "1")]
    pub page: i32,
    #[prost(int32, tag = "2")]
    pub page_size: i32,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTemplatesResponse {
    #[prost(message, repeated, tag = "1")]
    pub templates: ::prost::alloc::vec::Vec<MessageTemplate>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageTemplate {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub title_template: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub content_template: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "6")]
    pub variables: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bool, tag = "7")]
    pub is_active: bool,
    #[prost(int64, tag = "8")]
    pub created_at: i64,
    #[prost(int64, tag = "9")]
    pub updated_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTemplateRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub title_template: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub content_template: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "5")]
    pub variables: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bool, tag = "6")]
    pub is_active: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTemplateResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateTemplateRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub title_template: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub content_template: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "6")]
    pub variables: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(bool, tag = "7")]
    pub is_active: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTemplateResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteTemplateRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteTemplateResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
