// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Report {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "ReportType", tag = "4")]
    pub report_type: i32,
    /// 数据源名称
    #[prost(string, tag = "5")]
    pub data_source: ::prost::alloc::string::String,
    /// SQL/查询模板
    #[prost(string, tag = "6")]
    pub query_template: ::prost::alloc::string::String,
    /// 图表配置等
    #[prost(map = "string, string", tag = "7")]
    pub config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 权限配置 JSON
    #[prost(string, tag = "8")]
    pub permissions: ::prost::alloc::string::String,
    #[prost(int64, tag = "9")]
    pub created_by: i64,
    #[prost(int64, tag = "10")]
    pub created_at: i64,
    #[prost(int64, tag = "11")]
    pub updated_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListReportsRequest {
    #[prost(int32, tag = "1")]
    pub page: i32,
    #[prost(int32, tag = "2")]
    pub page_size: i32,
    #[prost(int64, tag = "3")]
    pub created_by: i64,
    #[prost(string, tag = "4")]
    pub keyword: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListReportsResponse {
    #[prost(message, repeated, tag = "1")]
    pub reports: ::prost::alloc::vec::Vec<Report>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetReportRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReportResponse {
    #[prost(message, optional, tag = "1")]
    pub report: ::core::option::Option<Report>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateReportRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "ReportType", tag = "3")]
    pub report_type: i32,
    #[prost(string, tag = "4")]
    pub data_source: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub query_template: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "6")]
    pub config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "7")]
    pub permissions: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateReportResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateReportRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub query_template: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "5")]
    pub config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "6")]
    pub permissions: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateReportResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteReportRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteReportResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenerateReportRequest {
    #[prost(int64, tag = "1")]
    pub report_id: i64,
    /// 查询参数
    #[prost(map = "string, string", tag = "2")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 异步生成
    #[prost(bool, tag = "3")]
    pub r#async: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GenerateReportResponse {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
    /// 同步生成时直接返回
    #[prost(message, optional, tag = "2")]
    pub data: ::core::option::Option<ReportData>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetReportDataRequest {
    #[prost(string, tag = "1")]
    pub task_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReportData {
    #[prost(string, repeated, tag = "1")]
    pub columns: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 使用 JSON 编码的行数据
    #[prost(string, tag = "2")]
    pub rows_json: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub total_count: i64,
    #[prost(int64, tag = "4")]
    pub generated_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetReportDataResponse {
    #[prost(message, optional, tag = "1")]
    pub data: ::core::option::Option<ReportData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExportReportRequest {
    #[prost(int64, tag = "1")]
    pub report_id: i64,
    #[prost(enumeration = "ExportFormat", tag = "2")]
    pub format: i32,
    #[prost(map = "string, string", tag = "3")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExportReportResponse {
    #[prost(string, tag = "1")]
    pub file_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub download_url: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub expires_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReportExecution {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub report_id: i64,
    #[prost(string, tag = "3")]
    pub report_name: ::prost::alloc::string::String,
    /// pending, running, success, failed
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub row_count: i32,
    #[prost(int64, tag = "6")]
    pub duration_ms: i64,
    #[prost(string, tag = "7")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub created_at: i64,
    #[prost(int64, tag = "9")]
    pub finished_at: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListExecutionsRequest {
    #[prost(int64, tag = "1")]
    pub report_id: i64,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListExecutionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub executions: ::prost::alloc::vec::Vec<ReportExecution>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
/// 报表类型
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReportType {
    /// 表格报表
    Table = 0,
    /// 图表报表
    Chart = 1,
    /// 仪表盘
    Dashboard = 2,
}
impl ReportType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Table => "TABLE",
            Self::Chart => "CHART",
            Self::Dashboard => "DASHBOARD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TABLE" => Some(Self::Table),
            "CHART" => Some(Self::Chart),
            "DASHBOARD" => Some(Self::Dashboard),
            _ => None,
        }
    }
}
/// 导出格式
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExportFormat {
    Pdf = 0,
    Excel = 1,
    Csv = 2,
    Html = 3,
}
impl ExportFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pdf => "PDF",
            Self::Excel => "EXCEL",
            Self::Csv => "CSV",
            Self::Html => "HTML",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PDF" => Some(Self::Pdf),
            "EXCEL" => Some(Self::Excel),
            "CSV" => Some(Self::Csv),
            "HTML" => Some(Self::Html),
            _ => None,
        }
    }
}
