// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tenant {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 租户代码
    #[prost(string, tag = "3")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub logo: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "TenantStatus", tag = "6")]
    pub status: i32,
    /// free, basic, pro, enterprise
    #[prost(string, tag = "7")]
    pub plan: ::prost::alloc::string::String,
    /// 最大用户数
    #[prost(int64, tag = "8")]
    pub max_users: i64,
    /// 当前用户数
    #[prost(int64, tag = "9")]
    pub current_users: i64,
    /// 过期时间
    #[prost(int64, tag = "10")]
    pub expires_at: i64,
    /// 自定义配置
    #[prost(map = "string, string", tag = "11")]
    pub config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(int64, tag = "12")]
    pub created_at: i64,
    #[prost(int64, tag = "13")]
    pub updated_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTenantsRequest {
    #[prost(int32, tag = "1")]
    pub page: i32,
    #[prost(int32, tag = "2")]
    pub page_size: i32,
    #[prost(string, tag = "3")]
    pub keyword: ::prost::alloc::string::String,
    #[prost(enumeration = "TenantStatus", tag = "4")]
    pub status: i32,
    #[prost(string, tag = "5")]
    pub plan: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTenantsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tenants: ::prost::alloc::vec::Vec<Tenant>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTenantRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTenantResponse {
    #[prost(message, optional, tag = "1")]
    pub tenant: ::core::option::Option<Tenant>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTenantRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub logo: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub plan: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub max_users: i64,
    #[prost(map = "string, string", tag = "7")]
    pub config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTenantResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTenantRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub logo: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "TenantStatus", tag = "5")]
    pub status: i32,
    #[prost(string, tag = "6")]
    pub plan: ::prost::alloc::string::String,
    #[prost(int64, tag = "7")]
    pub max_users: i64,
    #[prost(int64, tag = "8")]
    pub expires_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTenantResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteTenantRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(bool, tag = "2")]
    pub force: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteTenantResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TenantUser {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub tenant_id: i64,
    #[prost(int64, tag = "3")]
    pub user_id: i64,
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    /// owner, admin, member
    #[prost(string, tag = "5")]
    pub role: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub is_active: bool,
    #[prost(int64, tag = "7")]
    pub joined_at: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTenantUsersRequest {
    #[prost(int64, tag = "1")]
    pub tenant_id: i64,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTenantUsersResponse {
    #[prost(message, repeated, tag = "1")]
    pub users: ::prost::alloc::vec::Vec<TenantUser>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddTenantUserRequest {
    #[prost(int64, tag = "1")]
    pub tenant_id: i64,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
    #[prost(string, tag = "3")]
    pub role: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddTenantUserResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(bool, tag = "2")]
    pub success: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveTenantUserRequest {
    #[prost(int64, tag = "1")]
    pub tenant_id: i64,
    #[prost(int64, tag = "2")]
    pub user_id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveTenantUserResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetTenantConfigRequest {
    #[prost(int64, tag = "1")]
    pub tenant_id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTenantConfigResponse {
    #[prost(map = "string, string", tag = "1")]
    pub config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateTenantConfigRequest {
    #[prost(int64, tag = "1")]
    pub tenant_id: i64,
    #[prost(map = "string, string", tag = "2")]
    pub config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTenantConfigResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UsageStats {
    #[prost(int64, tag = "1")]
    pub tenant_id: i64,
    #[prost(int64, tag = "2")]
    pub users_count: i64,
    #[prost(int64, tag = "3")]
    pub storage_used: i64,
    #[prost(int64, tag = "4")]
    pub api_calls: i64,
    #[prost(int64, tag = "5")]
    pub period_start: i64,
    #[prost(int64, tag = "6")]
    pub period_end: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUsageStatsRequest {
    #[prost(int64, tag = "1")]
    pub tenant_id: i64,
    #[prost(int64, tag = "2")]
    pub period_start: i64,
    #[prost(int64, tag = "3")]
    pub period_end: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUsageStatsResponse {
    #[prost(message, optional, tag = "1")]
    pub stats: ::core::option::Option<UsageStats>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TenantStatus {
    Active = 0,
    Suspended = 1,
    Expired = 2,
    Pending = 3,
}
impl TenantStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Active => "ACTIVE",
            Self::Suspended => "SUSPENDED",
            Self::Expired => "EXPIRED",
            Self::Pending => "PENDING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTIVE" => Some(Self::Active),
            "SUSPENDED" => Some(Self::Suspended),
            "EXPIRED" => Some(Self::Expired),
            "PENDING" => Some(Self::Pending),
            _ => None,
        }
    }
}
