// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkflowNode {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration = "NodeType", tag = "3")]
    pub node_type: i32,
    #[prost(int32, tag = "4")]
    pub position_x: i32,
    #[prost(int32, tag = "5")]
    pub position_y: i32,
    /// 节点配置
    #[prost(map = "string, string", tag = "6")]
    pub config: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// 输出节点 ID
    #[prost(string, repeated, tag = "7")]
    pub outputs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkflowDefinition {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration = "WorkflowStatus", tag = "4")]
    pub status: i32,
    #[prost(string, tag = "5")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub nodes: ::prost::alloc::vec::Vec<WorkflowNode>,
    /// 全局变量
    #[prost(map = "string, string", tag = "7")]
    pub variables: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(int64, tag = "8")]
    pub created_at: i64,
    #[prost(int64, tag = "9")]
    pub updated_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListWorkflowsRequest {
    #[prost(int32, tag = "1")]
    pub page: i32,
    #[prost(int32, tag = "2")]
    pub page_size: i32,
    #[prost(string, tag = "3")]
    pub keyword: ::prost::alloc::string::String,
    #[prost(enumeration = "WorkflowStatus", tag = "4")]
    pub status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWorkflowsResponse {
    #[prost(message, repeated, tag = "1")]
    pub workflows: ::prost::alloc::vec::Vec<WorkflowDefinition>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetWorkflowRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWorkflowResponse {
    #[prost(message, optional, tag = "1")]
    pub workflow: ::core::option::Option<WorkflowDefinition>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateWorkflowRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub nodes: ::prost::alloc::vec::Vec<WorkflowNode>,
    #[prost(map = "string, string", tag = "4")]
    pub variables: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateWorkflowResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateWorkflowRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub nodes: ::prost::alloc::vec::Vec<WorkflowNode>,
    #[prost(map = "string, string", tag = "5")]
    pub variables: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(enumeration = "WorkflowStatus", tag = "6")]
    pub status: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateWorkflowResponse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteWorkflowRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteWorkflowResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkflowInstance {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub workflow_id: i64,
    #[prost(string, tag = "3")]
    pub workflow_name: ::prost::alloc::string::String,
    /// 业务关联键
    #[prost(string, tag = "4")]
    pub business_key: ::prost::alloc::string::String,
    #[prost(enumeration = "InstanceStatus", tag = "5")]
    pub status: i32,
    #[prost(map = "string, string", tag = "6")]
    pub variables: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "7")]
    pub current_node: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub started_by: i64,
    #[prost(int64, tag = "9")]
    pub started_at: i64,
    #[prost(int64, tag = "10")]
    pub finished_at: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartWorkflowRequest {
    #[prost(int64, tag = "1")]
    pub workflow_id: i64,
    #[prost(string, tag = "2")]
    pub business_key: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub variables: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartWorkflowResponse {
    #[prost(int64, tag = "1")]
    pub instance_id: i64,
    #[prost(string, tag = "2")]
    pub workflow_name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInstanceRequest {
    #[prost(int64, tag = "1")]
    pub id: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetInstanceResponse {
    #[prost(message, optional, tag = "1")]
    pub instance: ::core::option::Option<WorkflowInstance>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListInstancesRequest {
    #[prost(int64, tag = "1")]
    pub workflow_id: i64,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub page_size: i32,
    #[prost(enumeration = "InstanceStatus", tag = "4")]
    pub status: i32,
    #[prost(string, tag = "5")]
    pub business_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListInstancesResponse {
    #[prost(message, repeated, tag = "1")]
    pub instances: ::prost::alloc::vec::Vec<WorkflowInstance>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkflowTask {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub instance_id: i64,
    #[prost(string, tag = "3")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub assignee: ::prost::alloc::string::String,
    #[prost(enumeration = "TaskStatus", tag = "6")]
    pub status: i32,
    #[prost(string, tag = "7")]
    pub form_data: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub created_at: i64,
    #[prost(int64, tag = "9")]
    pub completed_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTasksRequest {
    #[prost(int64, tag = "1")]
    pub instance_id: i64,
    /// 用户 ID
    #[prost(string, tag = "2")]
    pub assignee: ::prost::alloc::string::String,
    #[prost(enumeration = "TaskStatus", tag = "3")]
    pub status: i32,
    #[prost(int32, tag = "4")]
    pub page: i32,
    #[prost(int32, tag = "5")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTasksResponse {
    #[prost(message, repeated, tag = "1")]
    pub tasks: ::prost::alloc::vec::Vec<WorkflowTask>,
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompleteTaskRequest {
    #[prost(int64, tag = "1")]
    pub task_id: i64,
    /// approve, reject
    #[prost(string, tag = "2")]
    pub action: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub variables: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "4")]
    pub comment: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompleteTaskResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub next_node: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelInstanceRequest {
    #[prost(int64, tag = "1")]
    pub instance_id: i64,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelInstanceResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// 节点类型
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeType {
    NodeStart = 0,
    NodeEnd = 1,
    /// 人工任务
    NodeTask = 2,
    /// 服务节点
    NodeService = 3,
    /// 网关
    NodeGateway = 4,
    /// 子流程
    NodeSubprocess = 5,
}
impl NodeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::NodeStart => "NODE_START",
            Self::NodeEnd => "NODE_END",
            Self::NodeTask => "NODE_TASK",
            Self::NodeService => "NODE_SERVICE",
            Self::NodeGateway => "NODE_GATEWAY",
            Self::NodeSubprocess => "NODE_SUBPROCESS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NODE_START" => Some(Self::NodeStart),
            "NODE_END" => Some(Self::NodeEnd),
            "NODE_TASK" => Some(Self::NodeTask),
            "NODE_SERVICE" => Some(Self::NodeService),
            "NODE_GATEWAY" => Some(Self::NodeGateway),
            "NODE_SUBPROCESS" => Some(Self::NodeSubprocess),
            _ => None,
        }
    }
}
/// 流程状态
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WorkflowStatus {
    WorkflowDraft = 0,
    WorkflowActive = 1,
    WorkflowSuspended = 2,
    WorkflowArchived = 3,
}
impl WorkflowStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::WorkflowDraft => "WORKFLOW_DRAFT",
            Self::WorkflowActive => "WORKFLOW_ACTIVE",
            Self::WorkflowSuspended => "WORKFLOW_SUSPENDED",
            Self::WorkflowArchived => "WORKFLOW_ARCHIVED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WORKFLOW_DRAFT" => Some(Self::WorkflowDraft),
            "WORKFLOW_ACTIVE" => Some(Self::WorkflowActive),
            "WORKFLOW_SUSPENDED" => Some(Self::WorkflowSuspended),
            "WORKFLOW_ARCHIVED" => Some(Self::WorkflowArchived),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InstanceStatus {
    InstanceRunning = 0,
    InstanceCompleted = 1,
    InstanceCancelled = 2,
    InstanceFailed = 3,
}
impl InstanceStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::InstanceRunning => "INSTANCE_RUNNING",
            Self::InstanceCompleted => "INSTANCE_COMPLETED",
            Self::InstanceCancelled => "INSTANCE_CANCELLED",
            Self::InstanceFailed => "INSTANCE_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INSTANCE_RUNNING" => Some(Self::InstanceRunning),
            "INSTANCE_COMPLETED" => Some(Self::InstanceCompleted),
            "INSTANCE_CANCELLED" => Some(Self::InstanceCancelled),
            "INSTANCE_FAILED" => Some(Self::InstanceFailed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TaskStatus {
    TaskPending = 0,
    TaskCompleted = 1,
    TaskRejected = 2,
    TaskSkipped = 3,
}
impl TaskStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TaskPending => "TASK_PENDING",
            Self::TaskCompleted => "TASK_COMPLETED",
            Self::TaskRejected => "TASK_REJECTED",
            Self::TaskSkipped => "TASK_SKIPPED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TASK_PENDING" => Some(Self::TaskPending),
            "TASK_COMPLETED" => Some(Self::TaskCompleted),
            "TASK_REJECTED" => Some(Self::TaskRejected),
            "TASK_SKIPPED" => Some(Self::TaskSkipped),
            _ => None,
        }
    }
}
